### ISSUE TITLE
IsDefined gets converted to enum instead of const

### ISSUE THREAD

**Issue by dbartholomae** [epiphone/class-validator-jsonschema#41]
[This line](https://github.com/epiphone/class-validator-jsonschema/blob/master/src/defaultConverters.ts#L45) is
```
      return { ...schema, enum: [meta.constraints[0]] }
```
but should be
```
      return { ...schema, const: meta.constraints[0] }
```
Similar for line 51.

**Comment by epiphone** [comment]
OpenAPI doesn't support `const`, hence the workaround of a single-item enum. Check https://swagger.io/docs/specification/data-models/keywords/.

**Comment by dbartholomae** [comment]
Thanks, that makes sense. I will then overwrite it via `additionalConverters` for my use case. Should I add some documentation on this in the README, or is this issue enough?

**Comment by epiphone** [comment]
This issue should do it.

In a future version this library would ideally support the latest JSON Schema draft, considering that OpenAPI v3.1.0 will be 100% compatible with JSON Schema instead of supporting a strange subset of it. That'll take some work here and in routing-controllers-openapi too though.
